In [1]:
import numpy as np

In [2]:
x = np.random.randn(1000000)

In [4]:
x =np.array([12,13,9,10,6,7])

In [5]:
x

array([12, 13,  9, 10,  6,  7])

In [6]:
np.shape(x)

(6,)

In [15]:
x = np.zeros([6,6])
x

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.empty([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
x[1:-1,1:-1]
x

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
x[0:-2,0:-2]
x

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [37]:
x =np.random.randn(6,6)
x

array([[-0.17205571,  0.28362385,  0.54816684, -1.82916829,  0.75441165,
         0.57171754],
       [-1.32145897,  0.53460955, -1.77201539,  0.00283018, -0.87085203,
        -1.1508141 ],
       [ 1.17348462,  0.20437831,  1.09146296, -0.04073173,  0.63366661,
        -0.24467519],
       [ 0.35263143, -2.37196253,  0.64196067,  0.10390767,  0.15390659,
        -0.51691779],
       [-2.05995476, -0.70945122, -0.20821952,  0.43732151, -1.45355372,
         0.91800319],
       [-0.6408203 , -1.32841524,  0.46947871,  0.64468078, -0.58564575,
         1.20734052]])

In [38]:
y = np.random.randn(6,6)
y

array([[ 1.96510966,  0.11207915, -0.18871655,  0.28371518,  0.31562265,
         0.7264026 ],
       [ 1.2763512 ,  0.76841324, -0.30329338,  1.66247169,  0.74863989,
         1.02020572],
       [-0.23086667, -0.41437013, -0.02362738, -2.03860358, -0.1071293 ,
         0.54180299],
       [-0.3491705 , -0.54545347, -1.02456577,  0.62972704,  2.14479118,
        -0.0305521 ],
       [ 0.80228451,  0.71285403,  0.03223892,  1.79614514, -0.79817298,
         0.49636599],
       [ 0.04686065,  0.47188804,  0.03423636, -0.34825965, -0.13320108,
         0.58757664]])

In [39]:
x+y

array([[ 1.79305395,  0.395703  ,  0.3594503 , -1.54545311,  1.0700343 ,
         1.29812014],
       [-0.04510778,  1.3030228 , -2.07530877,  1.66530186, -0.12221213,
        -0.13060839],
       [ 0.94261795, -0.20999182,  1.06783558, -2.0793353 ,  0.52653731,
         0.2971278 ],
       [ 0.00346093, -2.917416  , -0.38260509,  0.73363472,  2.29869777,
        -0.54746989],
       [-1.25767025,  0.00340281, -0.17598061,  2.23346666, -2.2517267 ,
         1.41436918],
       [-0.59395965, -0.8565272 ,  0.50371508,  0.29642113, -0.71884682,
         1.79491716]])

In [40]:
x-y

array([[-2.13716538,  0.17154469,  0.73688339, -2.11288347,  0.438789  ,
        -0.15468507],
       [-2.59781017, -0.23380369, -1.46872201, -1.65964151, -1.61949192,
        -2.17101982],
       [ 1.4043513 ,  0.61874843,  1.11509034,  1.99787185,  0.74079591,
        -0.78647817],
       [ 0.70180193, -1.82650907,  1.66652644, -0.52581937, -1.9908846 ,
        -0.48636569],
       [-2.86223928, -1.42230525, -0.24045844, -1.35882363, -0.65538074,
         0.4216372 ],
       [-0.68768095, -1.80030327,  0.43524235,  0.99294042, -0.45244467,
         0.61976388]])

In [44]:
2*x

array([[-0.34411142,  0.56724769,  1.09633369, -3.65833658,  1.5088233 ,
         1.14343508],
       [-2.64291795,  1.06921911, -3.54403078,  0.00566035, -1.74170405,
        -2.30162821],
       [ 2.34696925,  0.40875661,  2.18292593, -0.08146345,  1.26733321,
        -0.48935037],
       [ 0.70526286, -4.74392507,  1.28392135,  0.20781535,  0.30781317,
        -1.03383558],
       [-4.11990953, -1.41890244, -0.41643905,  0.87464303, -2.90710745,
         1.83600638],
       [-1.28164059, -2.65683047,  0.93895742,  1.28936155, -1.17129149,
         2.41468104]])

In [45]:
x/2

array([[-0.08602786,  0.14181192,  0.27408342, -0.91458415,  0.37720583,
         0.28585877],
       [-0.66072949,  0.26730478, -0.8860077 ,  0.00141509, -0.43542601,
        -0.57540705],
       [ 0.58674231,  0.10218915,  0.54573148, -0.02036586,  0.3168333 ,
        -0.12233759],
       [ 0.17631572, -1.18598127,  0.32098034,  0.05195384,  0.07695329,
        -0.25845889],
       [-1.02997738, -0.35472561, -0.10410976,  0.21866076, -0.72677686,
         0.4590016 ],
       [-0.32041015, -0.66420762,  0.23473936,  0.32234039, -0.29282287,
         0.60367026]])

In [46]:
a =np.array([8,9,11,13,40])

In [47]:
b = np.array([5,6,7,8,9])

In [50]:
np.cumsum(a)

array([ 8, 17, 28, 41, 81], dtype=int32)

In [52]:
np.cumprod(a)

array([     8,     72,    792,  10296, 411840], dtype=int32)

In [53]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x @ y

array([[ 1.16807729,  1.77681074,  1.85149494, -0.69074316, -4.5021857 ,
         1.22764848],
       [-2.25895016, -0.16842621,  0.058731  ,  2.9646799 ,  1.0274328 ,
        -2.48312203],
       [ 2.82603963,  0.19477027, -0.2554467 , -0.35463393, -0.1540892 ,
         1.82429766],
       [-2.41973284, -2.24002531,  0.51848945, -4.63008334, -1.56434992,
        -2.04643056],
       [-6.18132016, -1.53126518,  0.14534254, -3.99450968,  0.81688616,
        -2.52841515],
       [-3.70157479, -1.48652615, -0.1253231 , -4.41374397,  0.44227622,
        -1.16737128]])

In [57]:
x.shape

(6, 6)

In [60]:
x.reshape(4,9)

array([[-0.17205571,  0.28362385,  0.54816684, -1.82916829,  0.75441165,
         0.57171754, -1.32145897,  0.53460955, -1.77201539],
       [ 0.00283018, -0.87085203, -1.1508141 ,  1.17348462,  0.20437831,
         1.09146296, -0.04073173,  0.63366661, -0.24467519],
       [ 0.35263143, -2.37196253,  0.64196067,  0.10390767,  0.15390659,
        -0.51691779, -2.05995476, -0.70945122, -0.20821952],
       [ 0.43732151, -1.45355372,  0.91800319, -0.6408203 , -1.32841524,
         0.46947871,  0.64468078, -0.58564575,  1.20734052]])